### ISSUE TITLE
delighted to see this

### ISSUE THREAD

**Issue by dtaht** [muxamilian/fq-detection-simple#1]
But a gigabyte? wow...

**Comment by muxamilian** [comment]
Using python, I think sending more than a Gbit/s is not so easily possible. But at least no compilation is required and it's cross-platform.

**Comment by dtaht** [comment]
For mmy network, I upped teh timeout to 500, from 50, which was waaay too low.

**Comment by dtaht** [comment]
so far no luck in running this
timesout

**Comment by muxamilian** [comment]
The timeout is 5 seconds by default and it should only relevant to end the test after the measurement is done. 
The procedure is to run the server, and then run the client to connect to the server. The timeout shouldn't be relevant there. 
You can also run the server with the `--debug` option to see what's going on.

**Comment by dtaht** [comment]
running the server on zerg.taht.net
with a 500 timeout 
root@zerg:~/git/fq-detection-simple# 
root@zerg:~/git/fq-detection-simple# Traceback (most recent call last):
  File "/root/git/fq-detection-simple/./server.py", line 101, in <module>
    latest_rtts[sock_index] = current_time - send_times[sock_index][ack_num]
KeyError: 0

**Comment by dtaht** [comment]
trying it over ipv6 now... (this is via starlink)

root@zerg:~/git/fq-detection-simple# ./server.py --debug

Start cycle_num=0,rates=[15, 30]:[0.1, 0.3],123.91004061698914

just sits there, client times out

**Comment by muxamilian** [comment]
Thanks, looks to me as if your RTT is very high. Do you know any numbers? Will test locally with very high RTTs then.

**Comment by dtaht** [comment]
120+ms

**Comment by muxamilian** [comment]
That's not so high. I tested with 100 ms. Will test with a bit higher then. Your output seems to tell me that the RTT is 123 seconds. Will investigate.

**Comment by dtaht** [comment]
thatś the starlink minimum. It can go higher than 3s. I left that server zerg.taht.net running if you can test against it.

**Comment by muxamilian** [comment]
I added a demo video of running it on zerg and lqos to the [readme](https://github.com/muxamilian/fq-detection-simple#short-video). 

To reproduce, go to my home dir on zerg and run `sudo bash maxnet.sh fq_codel 242.0.0`. Also run `sudo bash maxnet.sh pfifo 243.0.0`.

Then you should be able to reproduce everything exactly like in the video.  

I have one weird glitch with the network namespaces: After using them once, they break and have to be reinitialized. This means that you have to run `sudo bash maxnet.sh fq_codel 242.0.0` and `sudo bash maxnet.sh fq_codel 243.0.0` each time you before you start the server on zerg.

**Comment by muxamilian** [comment]
There's a faster (can test up to a higher bandwidth) C version now: https://github.com/muxamilian/fq-detection-fast
The Python is also more performant (`send` is twice as fast as `sendto`).

**Comment by dtaht** [comment]
i am going to be retiring zerg soon.

**Comment by muxamilian** [comment]
Thanks for the info
